version: '3.7'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: run
    environment:
      HALLMONITOR_CONFIG: ./examples/helloworld/config.yaml
    ports:
        - "5001:5001"
  test_api:
    build:
      context: .
      dockerfile: ./examples/helloworld/Dockerfile
      target: run
    environment:
      HALLMONITOR_CONFIG: ./examples/helloworld/config.yaml
    ports:
        - "5000:5000"
